contents: |
  [Unit]
  Description=Configures SRIOV NIC
  Before=kubelet.service
  
  [Service]
  Type=oneshot
  ExecStart=/var/lib/sriov/sriov-network-config-daemon service -v 2
  StandardOutput=journal+console
  
  [Install]
  WantedBy=multi-user.target
enabled: true
name: sriov-config.service
