// Code generated by MockGen. DO NOT EDIT.
// Source: orchestration.go
//
// Generated by this command:
//
//	mockgen -destination mock/mock_orchestration.go -source orchestration.go
//

// Package mock_orchestrator is a generated GoMock package.
package mock_orchestrator

import (
	context "context"
	reflect "reflect"

	consts "github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/consts"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockOrchestrationInterface is a mock of OrchestrationInterface interface.
type MockOrchestrationInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrchestrationInterfaceMockRecorder
	isgomock struct{}
}

// MockOrchestrationInterfaceMockRecorder is the mock recorder for MockOrchestrationInterface.
type MockOrchestrationInterfaceMockRecorder struct {
	mock *MockOrchestrationInterface
}

// NewMockOrchestrationInterface creates a new mock instance.
func NewMockOrchestrationInterface(ctrl *gomock.Controller) *MockOrchestrationInterface {
	mock := &MockOrchestrationInterface{ctrl: ctrl}
	mock.recorder = &MockOrchestrationInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrchestrationInterface) EXPECT() *MockOrchestrationInterfaceMockRecorder {
	return m.recorder
}

// AfterCompleteDrainNode mocks base method.
func (m *MockOrchestrationInterface) AfterCompleteDrainNode(arg0 context.Context, arg1 *v1.Node) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterCompleteDrainNode", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AfterCompleteDrainNode indicates an expected call of AfterCompleteDrainNode.
func (mr *MockOrchestrationInterfaceMockRecorder) AfterCompleteDrainNode(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterCompleteDrainNode", reflect.TypeOf((*MockOrchestrationInterface)(nil).AfterCompleteDrainNode), arg0, arg1)
}

// BeforeDrainNode mocks base method.
func (m *MockOrchestrationInterface) BeforeDrainNode(arg0 context.Context, arg1 *v1.Node) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeDrainNode", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeforeDrainNode indicates an expected call of BeforeDrainNode.
func (mr *MockOrchestrationInterfaceMockRecorder) BeforeDrainNode(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeDrainNode", reflect.TypeOf((*MockOrchestrationInterface)(nil).BeforeDrainNode), arg0, arg1)
}

// ClusterType mocks base method.
func (m *MockOrchestrationInterface) ClusterType() consts.ClusterType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterType")
	ret0, _ := ret[0].(consts.ClusterType)
	return ret0
}

// ClusterType indicates an expected call of ClusterType.
func (mr *MockOrchestrationInterfaceMockRecorder) ClusterType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterType", reflect.TypeOf((*MockOrchestrationInterface)(nil).ClusterType))
}

// Flavor mocks base method.
func (m *MockOrchestrationInterface) Flavor() consts.ClusterFlavor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flavor")
	ret0, _ := ret[0].(consts.ClusterFlavor)
	return ret0
}

// Flavor indicates an expected call of Flavor.
func (mr *MockOrchestrationInterfaceMockRecorder) Flavor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flavor", reflect.TypeOf((*MockOrchestrationInterface)(nil).Flavor))
}
